# Generated by Django 5.1.5 on 2025-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
